### ISSUE TITLE
Modular Distance functions

### ISSUE THREAD

**Issue by Jorisvansteenbrugge** [Jorisvansteenbrugge/TcT#2]

**Comment by StephanHeijl** [comment]
Waarom is dit nog steeds niet af gemaakt?

-t Stephan en Björn

**Comment by Jorisvansteenbrugge** [comment]
Due to a shortcomming in time, this issue has not been fully adressed.

**Comment by Jorisvansteenbrugge** [comment]
@StephanHeijl I would like to inform you that this issue has been resolved in commit https://github.com/Jorisvansteenbrugge/TcT/commit/44bf3b20635c71bb27bd4689512bf488061991dd. Thank you for your patience.

**Comment by StephanHeijl** [comment]
Thanks, I really needed `Modular Distance functions` for my own project ;)
